Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

    # Увеличиваем время ожидания загрузки и SSH
  config.vm.boot_timeout = 900    # 15 минут
  config.ssh.insert_key = true

  # Отключаем фоновые обновления Ubuntu, которые мешают загрузке
  config.vm.provision "shell", inline: <<-SHELL
    sudo systemctl mask apt-daily.service apt-daily-upgrade.service
    sudo systemctl stop apt-daily.service apt-daily-upgrade.service
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
  SHELL

  config.vm.define "consul" do |consul|
    consul.vm.hostname = "consul"
    consul.vm.network "private_network", ip: "192.168.56.10"
    consul.vm.network "forwarded_port", guest: 8500, host: 8500, id: "consul_ui"
  end

  config.vm.define "api" do |api|
    api.vm.hostname = "api"
    api.vm.network "private_network", ip: "192.168.56.11"
    api.vm.network "forwarded_port", guest: 8082, host: 8082, id: "app"
    api.vm.provider "virtualbox" do |v| # for docker-compose better performance
      v.memory = "4096"
    end
  end

 config.vm.define "manager" do |manager|
  manager.vm.hostname = "manager"
  manager.vm.network "private_network", ip: "192.168.56.12"

  # Синхронизировать текущую папку проекта с /home/vagrant/ansible02
  manager.vm.synced_folder ".", "/home/vagrant/ansible02"

  manager.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get install -y ansible
  SHELL
end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.13"
  end
end